#pragma once

namespace OpenEFT {

    template <typename Enum>
    struct EnumTraits;

#define DEFINE_ENUM_TRAITS(NAME, ...)                   \
    template <>                                         \
    struct EnumTraits<NAME> {                           \
        static constexpr NAME values[] = {__VA_ARGS__}; \
    };

    DEFINE_ENUM_TRAITS(VALUE_TYPE, VALUE_TYPE::UNKNOWN, VALUE_TYPE::BOOL,
                       VALUE_TYPE::INTEGER, VALUE_TYPE::UINT,
                       VALUE_TYPE::FLOAT, VALUE_TYPE::STRING,
                       VALUE_TYPE::HEX_BINARY, VALUE_TYPE::B64_BINARY,
                       VALUE_TYPE::BINARY, VALUE_TYPE::DATE, VALUE_TYPE::TIME,
                       VALUE_TYPE::DATE_TIME, VALUE_TYPE::ENUM,
                       VALUE_TYPE::COMPOSITE)

    DEFINE_ENUM_TRAITS(RULE_PRESENCE, RULE_PRESENCE::UNKNOWN,
                       RULE_PRESENCE::OPTIONAL, RULE_PRESENCE::MANDATORY,
                       RULE_PRESENCE::CONDITIONAL, RULE_PRESENCE::FORBIDDEN)

    DEFINE_ENUM_TRAITS(CHAR_ENCODING, CHAR_ENCODING::UNKNOWN,
                       CHAR_ENCODING::ASCII7, CHAR_ENCODING::UTF8,
                       CHAR_ENCODING::BINARY)

    DEFINE_ENUM_TRAITS(COMPARISON_OP, COMPARISON_OP::UNKNOWN,
                       COMPARISON_OP::EQUAL, COMPARISON_OP::NOT_EQUAL,
                       COMPARISON_OP::LESS, COMPARISON_OP::LESS_EQUAL,
                       COMPARISON_OP::GREATER, COMPARISON_OP::GREATER_EQUAL,
                       COMPARISON_OP::IN_SET, COMPARISON_OP::NOT_IN_SET,
                       COMPARISON_OP::MATCH_REGEX)

    DEFINE_ENUM_TRAITS(DEPENDENCY_OP, DEPENDENCY_OP::UNKNOWN,
                       DEPENDENCY_OP::EXISTS, DEPENDENCY_OP::NOT_EXISTS,
                       DEPENDENCY_OP::EQUALS, DEPENDENCY_OP::NOT_EQUALS,
                       DEPENDENCY_OP::IN_SET)

    DEFINE_ENUM_TRAITS(EXCLUSIVITY_TYPE, EXCLUSIVITY_TYPE::UNKNOWN,
                       EXCLUSIVITY_TYPE::MUTUALLY_EXCLUSIVE,
                       EXCLUSIVITY_TYPE::ONE_REQUIRED,
                       EXCLUSIVITY_TYPE::EXACTLY_ONE_REQUIRED,
                       EXCLUSIVITY_TYPE::AT_LEAST_ONE_REQUIRED)

    DEFINE_ENUM_TRAITS(CONDITION_LOGIC, CONDITION_LOGIC::UNKNOWN,
                       CONDITION_LOGIC::AND, CONDITION_LOGIC::OR)

    DEFINE_ENUM_TRAITS(UNKNOWN_FIELD_POLICY, UNKNOWN_FIELD_POLICY::UNKNOWN,
                       UNKNOWN_FIELD_POLICY::IGNORE, UNKNOWN_FIELD_POLICY::WARN,
                       UNKNOWN_FIELD_POLICY::ERROR)

    DEFINE_ENUM_TRAITS(SEMANTIC_RULE_TYPE, SEMANTIC_RULE_TYPE::UNKNOWN,
                       SEMANTIC_RULE_TYPE::FIELD_EQUALS_COMPUTED_VALUE,
                       SEMANTIC_RULE_TYPE::FIELD_MATCHES_COUNT,
                       SEMANTIC_RULE_TYPE::FIELD_MATCHES_RECORD_COUNT,
                       SEMANTIC_RULE_TYPE::CUSTOM_VALIDATOR_HOOK)

    DEFINE_ENUM_TRAITS(CONSTRAINT_TYPE, CONSTRAINT_TYPE::UNKNOWN,
                       CONSTRAINT_TYPE::NUMERIC, CONSTRAINT_TYPE::ENUM,
                       CONSTRAINT_TYPE::PATTERN)

}  // namespace OpenEFT
