RECORDS = {
"1.001":"LEN", # LOGICAL RECORD LENGTH
"1.002":"VER", # VERSION
"1.003":"CNT", # FILE CONTENT
"1.004":"TOT", # TYPE OF TRANSACTION
"1.005":"DAT", # DATE
"1.006":"PRY", # TRANSACTION PRIORITY
"1.007":"DAI", # DESTINATION AGENCY IDENTIFIER
"1.008":"ORI", # ORIGINATING AGENCY IDENTIFIER
"1.009":"TCN", # TRANSACTION CONTROL NUMBER
"1.010":"TCR", # TRANSACTION CONTROL REFERENCE
"1.011":"NSR", # NATIVE SCANNING RESOLUTION
"1.012":"NTR", # NOMINAL TRANSMITTING RESOLUTION
"2.001":"LEN", # LOGICAL RECORD LENGTH
"2.002":"IDC", # IMAGE DESIGNATION CHARACTER
"2.003":"FFN", # FBI FILE NUMBER
"2.004":"QDD", # QUERY DEPTH OF DETAIL
"2.005":"RET", # RETENTION CODE
"2.006":"ATN", # “ATTENTION” INDICATOR
"2.007":"SCO", # SEND COPY TO
"2.009":"OCA", # ORIGINATING AGENCY CASE NUMBER
"2.010":"CIN", # CONTRIBUTOR CASE IDENTIFIER NUMBER
"2.010A":"CIN_PRE", # CONTRIBUTOR CASE PREFIX
"2.010B":"CIN_ID", # CONTRIBUTOR CASE ID
"2.011":"CIX", # CONTRIBUTOR CASE IDENTIFIER EXTENSION
"2.012":"LCN", # FBI LATENT CASE NUMBER
"2.013":"LCX", # FBI LATENT CASE EXTENSION
"2.014":"FBI", # FBI NUMBER
"2.015":"SID", # STATE IDENTIFICATION NUMBER
"2.016":"SOC", # SOCIAL SECURITY ACCOUNT NUMBER
"2.017":"MNU", # MISCELLANEOUS IDENTIFICATION NUMBER
"2.018":"NAM", # NAME
"2.019":"AKA", # ALIASES
"2.020":"POB", # PLACE OF BIRTH
"2.021":"CTZ", # COUNTRY OF CITIZENSHIP
"2.022":"DOB", # DATE OF BIRTH
"2.023":"AGR", # AGE RANGE
"2.024":"SEX", # SEX
"2.025":"RAC", # RACE
"2.026":"SMT", # SCARS, MARKS, AND TATTOOS
"2.027":"HGT", # HEIGHT
"2.028":"HTR", # HEIGHT RANGE
"2.029":"WGT", # WEIGHT
"2.030":"WTR", # WEIGHT RANGE
"2.031":"EYE", # COLOR EYES
"2.032":"HAI", # HAIR COLOR
"2.033":"FPC", # NCIC FINGERPRINT CLASSIFICATION
"2.034":"PAT", # PATTERN LEVEL CLASSIFICATIONS
"2.034A":"FGP", # FINGER NUMBER
"2.034B":"PATCL", # PATTERN CLASSIFICATION CODE    
"2.035":"PPA", # “PALM PRINTS AVAILABLE” INDICATOR
"2.036":"PHT", # “PHOTO AVAILABLE” INDICATOR
"2.037":"RFP", # REASON FINGERPRINTED
"2.038":"DPR", # DATE PRINTED
"2.039":"EAD", # EMPLOYER AND ADDRESS
"2.040":"OCP", # OCCUPATION
"2.041":"RES", # RESIDENCE OF PERSON FINGERPRINTED
"2.042":"MIL", # MILITARY CODE
"2.043":"TSR", # TYPE OF SEARCH REQUESTED
"2.044":"GEO", # GEOGRAPHICAL AREA OF SEARCH
"2.045":"DOA", # DATE OF ARREST
"2.046":"DOS", # DATE OF ARREST-SUFFIX
"2.047":"ASL", # ARREST SEGMENT LITERAL
"2.047A":"DOO", # DATE OF OFFENSE
"2.047B":"AOL", # ARREST OFFENSE LITERAL
"2.048":"CSR", # CIVIL SEARCH REQUESTED INDICATOR
"2.049":"EID", # EMPLOYEE IDENTIFICATION NUMBER
"2.051":"CSL", # COURT SEGMENT LITERAL
"2.051A":"CDD", # COURT DISPOSITION DATE
"2.051B":"COL", # COURT OFFENSE LITERAL
"2.051C":"CPL", # OTHER COURT SENTENCE PROVISION LITERAL
"2.052":"RBR", # RAP BACK REQUEST
"2.053":"OFC", # OFFENSE CATEGORY
"2.054":"SSD", # CUSTODY OR SUPERVISORY STATUS - START DATE
"2.055":"SLE", # CUSTODY OR SUPERVISORY STATUS LITERAL
"2.056":"ICO", # IDENTIFICATION COMMENTS
"2.057":"FNR", # FINGER NUMBER(S) REQUESTED 
"2.059":"SRF", # SEARCH RESULTS FINDINGS
"2.060":"MSG", # STATUS/ERROR MESSAGE
"2.061":"CST", # CASE TITLE
"2.062":"IMT", # IMAGE TYPE (IF TYPE -7 IMAGES)
"2.063":"PTD", # PERSON TYPE DESIGNATOR
"2.064":"CAN", # CANDIDATE LIST
"2.064A":"FNU", # FBI NUMBER
"2.064B":"NAM", # NAME
"2.065":"RSR", # REPOSITORY STATISTICS RESPONSE
"2.067":"IMA", # IMAGE CAPTURE EQUIPMENT
"2.067A":"MAK", # ORIGINATING FINGERPRINT READING SYSTEM MAKE
"2.067B":"MODL", # ORIGINATING FINGERPRINT READING SYSTEM MODEL
"2.067C":"SERNO", # ORIGINATING FINGERPRINT READING SYSTEM SERIAL
"2.069":"ETC", # ESTIMATED TIME TO COMPLETE
"2.070":"RAP", # REQUEST FOR ELECTRONIC RAP SHEET
"2.071":"ACN", # ACTION TO BE TAKEN
"2.072":"FIU", # FINGERPRINT IMAGE(S) UPDATED
"2.073":"CRI", # CONTROLLING AGENCY IDENTIFIER
"2.074":"FGP", # FINGER POSITION
"2.075":"ERS", # ELECTRONIC RAP SHEET
"2.076":"PRI", # PRIORITY
"2.077":"CFS", # CANCEL FP SEARCH
"2.078":"PEN", # PENETRATION QUERY RESPONSE
"2.079":"NCR", # NUMBER OF CANDIDATE'S IMAGES RETURNED
"2.080":"EXP", # RESPONSE EXPLANATION
"2.081":"UCN", # UNIVERSAL CONTROL NUMBER
"2.082":"REC", # RESPONSE CODE
"2.083":"ULF", # UNSOLVED LATENT FILE
"2.084":"AMP", # AMPUTATED OR BANDAGED
"2.084A":"FGP", # FINGER NUMBER
"2.084B":"AMPCD", # AMPUTATED OR BANDAGED CODE
"2.085":"CRN", # CIVIL RECORD NUMBER
"2.086":"SCNA", # AFIS SEGMENT CONTROL NUMBER
"2.087":"TAA", # TREAT AS ADULT
"2.088":"NOT", # NOTE FIELD
"2.089":"MSC", # MATCH SCORE
"2.091":"RCD1", # RIDGE CORE DELTA ONE FOR SUBPATTERN
"2.091A":"FGP", # FINGER NUMBER
"2.091B":"RCN1", # RIDGE COUNT NUMBER 1
"2.092":"RCD2", # RIDGE CORE DELTA TWO FOR SUBPATTERN
"2.092A":"FGP", # FINGER NUMBER
"2.092B":"RCN2", # RIDGE COUNT NUMBER 2
"2.093":"SPCN", # SPECIAL POPULATION COGNIZANT FILE NUMBER
"2.094":"CCN", # COURT CASE NUMBER
"2.0095":"RFR", # REQUEST FEATURES RECORD
"2.096":"RPR", # REQUEST PHOTO RECORD
"2.098":"NDR", # NAME OF DESIGNATED REPOSITORY
"2.099":"SAN", # STATE ARREST NUMBER
"2.2001":"NAM1", # NAME-ONE
"2.2002":"NAM2", # NAME-TWO
"2.2003":"NAM3", # NAME-THREE
"2.2004":"NAM4", # NAME-FOUR
"2.2005":"NAM5", # NAME-FIVE
"2.2006":"CSF", # CASCADED SEARCH FLAG
"2.2007":"SDOB", # SUBMITTED DATE OF BIRTH
"2.2008":"SNAM", # SUBMITTED NAME
"2.2009":"PTY", # PHOTO TYPE
"2.2010":"NIR", # NUMBER OF IMAGES REQUESTED
"2.2011":"RBVS", # RAP BACK VERIFICATION STATUS
"2.2012":"IIR", # IRIS IMAGES REQUESTED
"2.2013":"DMI", # DISPOSITION MAINTENANCE INDICATOR
"2.2014":"RBE", # RAP BACK ELIGIBILITY
"2.2015":"RBRO", # RAP BACK RECORD OWNER
"14.001":"LEN", # LOGICAL RECORD LENGTH
"14.002":"IDC", # IMAGE DESIGNATION CHARACTER
"14.003":"IMP", # IMPRESSION TYPE
"14.004":"SRC", # SOURCE AGENCY/ORI
"14.005":"LCD", # TENPRINT CAPTURE DATE
"14.006":"HLL", # HORIZONTAL LINE LENGTH
"14.007":"VLL", # VERTICAL LINE LENGTH
"14.008":"SLC", # SCALE UNITS
"14.009":"HPS", # HORIZONTAL PIXEL SCALE
"14.010":"VPS", # VERTICAL PIXEL SCALE
"14.011":"CGA", # COMPRESSION ALGORITHM
"14.012":"BPX", # BITS PER PIXEL
"14.013":"FGP", # FINGER POSITION
"14.014":"MCL", # MAJOR CASE PRINT
"14.015":"MCS", # MAJOR CASE PRINT SEGMENT POSITION(S)
"14.016":"SHPS", # SCAN HOR PIXEL SCALE
"14.017":"SVPS", # SCAN VERT PIXEL SCALE
"14.020":"COM", # COMMENT
"14.021":"SEG", # FINGERPRINT SEGMENT POSITION(S)
"14.022":"IQM", # IMAGE QUALLITY METRIC
"14.023":"SQM", # SEGMENTATION QUALITY METRIC
"14.024":"AFM", # ALTERNATE FINGERPRINT QUALITY METRIC
"14.030":"DMM", # DEVICE MONITORING MODE
"14.099":"DAT", # IMAGE DATA
"14.999":"DAT", # IMAGE DATA
}

DESCRIPTORS = {
    "LEN":"LOGICAL RECORD LENGTH",
    "VER":"VERSION",
    "CNT":"FILE CONTENT",
    "TOT":"TYPE OF TRANSACTION",
    "DAT":"DATE",
    "PRY":"TRANSACTION PRIORITY",
    "DAI":"DESTINATION AGENCY IDENTIFIER",
    "ORI":"ORIGINATING AGENCY IDENTIFIER",
    "TCN":"TRANSACTION CONTROL NUMBER",
    "TCR":"TRANSACTION CONTROL REFERENCE",
    "NSR":"NATIVE SCANNING RESOLUTION",
    "NTR":"NOMINAL TRANSMITTING RESOLUTION",
    "LEN":"LOGICAL RECORD LENGTH",
    "IDC":"IMAGE DESIGNATION CHARACTER",
    "FFN":"FBI FILE NUMBER",
    "QDD":"QUERY DEPTH OF DETAIL",
    "RET":"RETENTION CODE",
    "ATN":"“ATTENTION” INDICATOR",
    "SCO":"SEND COPY TO",
    "OCA":"ORIGINATING AGENCY CASE NUMBER",
    "CIN":"CONTRIBUTOR CASE IDENTIFIER NUMBER",
    "CIN_PRE":"CONTRIBUTOR CASE PREFIX",
    "CIN_ID":"CONTRIBUTOR CASE ID",
    "CIX":"CONTRIBUTOR CASE IDENTIFIER EXTENSION",
    "LCN":"FBI LATENT CASE NUMBER",
    "LCX":"FBI LATENT CASE EXTENSION",
    "FBI":"FBI NUMBER",
    "SID":"STATE IDENTIFICATION NUMBER",
    "SOC":"SOCIAL SECURITY ACCOUNT NUMBER",
    "MNU":"MISCELLANEOUS IDENTIFICATION NUMBER",
    "NAM":"NAME",
    "AKA":"ALIASES",
    "POB":"PLACE OF BIRTH",
    "CTZ":"COUNTRY OF CITIZENSHIP",
    "DOB":"DATE OF BIRTH",
    "AGR":"AGE RANGE",
    "SEX":"SEX",
    "RAC":"RACE",
    "SMT":"SCARS, MARKS, AND TATTOOS",
    "HGT":"HEIGHT",
    "HTR":"HEIGHT RANGE",
    "WGT":"WEIGHT",
    "WTR":"WEIGHT RANGE",
    "EYE":"COLOR EYES",
    "HAI":"HAIR COLOR",
    "FPC":"NCIC FINGERPRINT CLASSIFICATION",
    "PAT":"PATTERN LEVEL CLASSIFICATIONS",
    "FGP":"FINGER NUMBER",
    "PATCL":"PATTERN CLASSIFICATION CODE",
    "PPA":"“PALM PRINTS AVAILABLE” INDICATOR",
    "PHT":"“PHOTO AVAILABLE” INDICATOR",
    "RFP":"REASON FINGERPRINTED",
    "DPR":"DATE PRINTED",
    "EAD":"EMPLOYER AND ADDRESS",
    "OCP":"OCCUPATION",
    "RES":"RESIDENCE OF PERSON FINGERPRINTED",
    "MIL":"MILITARY CODE",
    "TSR":"TYPE OF SEARCH REQUESTED",
    "GEO":"GEOGRAPHICAL AREA OF SEARCH",
    "DOA":"DATE OF ARREST",
    "DOS":"DATE OF ARREST-SUFFIX",
    "ASL":"ARREST SEGMENT LITERAL",
    "DOO":"DATE OF OFFENSE",
    "AOL":"ARREST OFFENSE LITERAL",
    "CSR":"CIVIL SEARCH REQUESTED INDICATOR",
    "EID":"EMPLOYEE IDENTIFICATION NUMBER",
    "CSL":"COURT SEGMENT LITERAL",
    "CDD":"COURT DISPOSITION DATE",
    "COL":"COURT OFFENSE LITERAL",
    "CPL":"OTHER COURT SENTENCE PROVISION LITERAL",
    "RBR":"RAP BACK REQUEST",
    "OFC":"OFFENSE CATEGORY",
    "SSD":"CUSTODY OR SUPERVISORY STATUS - START DATE",
    "SLE":"CUSTODY OR SUPERVISORY STATUS LITERAL",
    "ICO":"IDENTIFICATION COMMENTS",
    "FNR":"FINGER NUMBER(S) REQUESTED",
    "SRF":"SEARCH RESULTS FINDINGS",
    "MSG":"STATUS/ERROR MESSAGE",
    "CST":"CASE TITLE",
    "IMT":"IMAGE TYPE (IF TYPE -7 IMAGES)",
    "PTD":"PERSON TYPE DESIGNATOR",
    "CAN":"CANDIDATE LIST",
    "FNU":"FBI NUMBER",
    "NAM":"NAME",
    "RSR":"REPOSITORY STATISTICS RESPONSE",
    "IMA":"IMAGE CAPTURE EQUIPMENT",
    "MAK":"ORIGINATING FINGERPRINT READING SYSTEM MAKE",
    "MODL":"ORIGINATING FINGERPRINT READING SYSTEM MODEL",
    "SERNO":"ORIGINATING FINGERPRINT READING SYSTEM SERIAL",
    "ETC":"ESTIMATED TIME TO COMPLETE",
    "RAP":"REQUEST FOR ELECTRONIC RAP SHEET",
    "ACN":"ACTION TO BE TAKEN",
    "FIU":"FINGERPRINT IMAGE(S) UPDATED",
    "CRI":"CONTROLLING AGENCY IDENTIFIER",
    "FGP":"FINGER POSITION",
    "ERS":"ELECTRONIC RAP SHEET",
    "PRI":"PRIORITY",
    "CFS":"CANCEL FP SEARCH",
    "PEN":"PENETRATION QUERY RESPONSE",
    "NCR":"NUMBER OF CANDIDATE'S IMAGES RETURNED",
    "EXP":"RESPONSE EXPLANATION",
    "UCN":"UNIVERSAL CONTROL NUMBER",
    "REC":"RESPONSE CODE",
    "ULF":"UNSOLVED LATENT FILE",
    "AMP":"AMPUTATED OR BANDAGED",
    "FGP":"FINGER NUMBER",
    "AMPCD":"AMPUTATED OR BANDAGED CODE",
    "CRN":"CIVIL RECORD NUMBER",
    "SCNA":"AFIS SEGMENT CONTROL NUMBER",
    "TAA":"TREAT AS ADULT",
    "NOT":"NOTE FIELD",
    "MSC":"MATCH SCORE",
    "RCD1":"RIDGE CORE DELTA ONE FOR SUBPATTERN",
    "FGP":"FINGER NUMBER",
    "RCN1":"RIDGE COUNT NUMBER 1",
    "RCD2":"RIDGE CORE DELTA TWO FOR SUBPATTERN",
    "FGP":"FINGER NUMBER",
    "RCN2":"RIDGE COUNT NUMBER 2",
    "SPCN":"SPECIAL POPULATION COGNIZANT FILE NUMBER",
    "CCN":"COURT CASE NUMBER",
    "RFR":"REQUEST FEATURES RECORD",
    "RPR":"REQUEST PHOTO RECORD",
    "NDR":"NAME OF DESIGNATED REPOSITORY",
    "SAN":"STATE ARREST NUMBER",
    "NAM1":"NAME-ONE",
    "NAM2":"NAME-TWO",
    "NAM3":"NAME-THREE",
    "NAM4":"NAME-FOUR",
    "NAM5":"NAME-FIVE",
    "CSF":"CASCADED SEARCH FLAG",
    "SDOB":"SUBMITTED DATE OF BIRTH",
    "SNAM":"SUBMITTED NAME",
    "PTY":"PHOTO TYPE",
    "NIR":"NUMBER OF IMAGES REQUESTED",
    "RBVS":"RAP BACK VERIFICATION STATUS",
    "IIR":"IRIS IMAGES REQUESTED",
    "DMI":"DISPOSITION MAINTENANCE INDICATOR",
    "RBE":"RAP BACK ELIGIBILITY",
    "RBRO":"RAP BACK RECORD OWNER",
    "IMP":"IMPRESSION TYPE",
    "SRC":"SOURCE AGENCY/ORI",
    "LCD":"TENPRINT CAPTURE DATE",
    "HLL":"HORIZONTAL LINE LENGTH",
    "VLL":"VERTICAL LINE LENGTH",
    "SLC":"SCALE UNITS",
    "HPS":"HORIZONTAL PIXEL SCALE",
    "VPS":"VERTICAL PIXEL SCALE",
    "CGA":"COMPRESSION ALGORITHM",
    "BPX":"BITS PER PIXEL",
    "FGP":"FINGER POSITION",
    "MCL":"MAJOR CASE PRINT",
    "MCS":"MAJOR CASE PRINT SEGMENT POSITION(S)",
    "SHPS":"SCAN HOR PIXEL SCALE",
    "SVPS":"SCAN VERT PIXEL SCALE",
    "COM":"COMMENT",
    "SEG":"FINGERPRINT SEGMENT POSITION(S)",
    "IQM":"IMAGE QUALLITY METRIC",
    "SQM":"SEGMENTATION QUALITY METRIC",
    "AFM":"ALTERNATE FINGERPRINT QUALITY METRIC",
    "DMM":"DEVICE MONITORING MODE",
    "DAT":"IMAGE DATA",
}